### PR TITLE
Update ocap terms.

### PR DESCRIPTION
**Pull request by mattcollier**
Is this being held back to not break things.  Do we need to do a 1.0 release of what is on master and then release this as 2.0 or something?

### CODE REVIEW

**Comment by dlongley** [comment]
Anyone have an answer here? We only care about did-client having potential issues against the test net ... veres-one node can be in full dev mode at this point.

**Review by msporny — APPROVED** [review]
LGTM

**Comment by msporny** [comment]
> Is this being held back to not break things. Do we need to do a 1.0 release of what is on master and then release this as 2.0 or something?

Here's our end goal:

* Latest did-client npm release works, at a minimum, against the production network.
* Latest did-client master branch works, at a minimum, against the test network.
* Branches are expected to work against local dev mode.

**Comment by mattcollier** [comment]
@dmitrizagidulin It appears to me that you might be best able to assess the impacts of merging this.  What do you think?

I don't know what version of this context is running on the test net, but it seems like we should either release or tag that commit so people working with the testnet know what what they are working with.

**Comment by dmitrizagidulin** [comment]
@mattcollier Ok, I double-checked, and I think it's safe to publish a new release. The various `did-io`, `did-client`, `did-veres-one` and `did-client-veres-one` libs aren't actually using this package.
(I'm going to refactor `did-io` to use it, based on the new release.)

**Comment by mattcollier** [comment]
@dmitrizagidulin are you in favor of the following approach:
1. Release current master as v1
2. Merge this PR
3. Release v2

**Comment by dmitrizagidulin** [comment]
@mattcollier absolutely, in favor of that plan. :) thanks!

**Pull request merged**
